retrieve_artgraph_artworks:
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_pwd: "artgraph"
  neo4j_db: "neo4j"
object_features_extraction:
  model_name: 'faster_rcnn_R_101_FPN_3x'
  is_pretrained: True
  weights: 'faster_rcnn_R_101_FPN_3x'
  dataset: 'coco_2017_train'
style_transfer_target_filter:
  evaluation_datasets:
    - ola
    - semart
    - artpedia
train_AdaIn:
  content_dataset: coco_train2017
  style_dataset: artgraph_images
  style_filter: artgraph_filter
  n_thread: 6